"""Authoritative field catalogue for the LC issue form."""

LC_INFORMATION_FIELDS = [
    {'key': 'lcType', 'label': 'Loại hình L/C', 'section': 'Thông tin chung', 'kind': 'select', 'required': True},
    {'key': 'issueMode', 'label': '40A: Hình thức L/C (Form of documentary credit)', 'section': 'Thông tin chung', 'kind': 'select', 'required': True},
    {'key': 'currency', 'label': '32B: Loại tiền (Currency)', 'section': 'Giá trị thư tín dụng', 'kind': 'select', 'required': True},
    {'key': 'amount', 'label': '32B: Số tiền (Currency, Amount)', 'section': 'Giá trị thư tín dụng', 'kind': 'text', 'required': True},
    {'key': 'positiveTolerance', 'label': '39A: Dung sai dương (%)', 'section': 'Giá trị thư tín dụng', 'kind': 'text', 'required': False},
    {'key': 'negativeTolerance', 'label': '39A: Dung sai âm (%)', 'section': 'Giá trị thư tín dụng', 'kind': 'text', 'required': False},
    {'key': 'applicantName', 'label': '50: Tên đầy đủ người yêu cầu phát hành', 'section': 'Applicant', 'kind': 'text', 'required': True},
    {'key': 'applicantTaxNo', 'label': '50: Mã số thuế người yêu cầu phát hành', 'section': 'Applicant', 'kind': 'text', 'required': False},
    {'key': 'applicantAddress', 'label': '50: Địa chỉ người yêu cầu phát hành', 'section': 'Applicant', 'kind': 'text', 'required': True},
    {'key': 'applicantCity', 'label': '50: Tỉnh/Thành phố người yêu cầu phát hành', 'section': 'Applicant', 'kind': 'text', 'required': False},
    {'key': 'applicantCountry', 'label': '50: Quốc gia người yêu cầu phát hành', 'section': 'Applicant', 'kind': 'text', 'required': True},
    {'key': 'applicantPostCode', 'label': '50: Mã bưu chính người yêu cầu phát hành', 'section': 'Applicant', 'kind': 'text', 'required': False},
    {'key': 'applicantDetailedAddress', 'label': '50: Địa chỉ chi tiết người yêu cầu phát hành', 'section': 'Applicant', 'kind': 'textarea', 'required': False},
    {'key': 'beneficiaryName', 'label': '59: Tên đầy đủ người thụ hưởng', 'section': 'Beneficiary', 'kind': 'text', 'required': True},
    {'key': 'beneficiaryTaxNo', 'label': '59: Mã số thuế người thụ hưởng', 'section': 'Beneficiary', 'kind': 'text', 'required': False},
    {'key': 'beneficiaryAddress', 'label': '59: Địa chỉ người thụ hưởng', 'section': 'Beneficiary', 'kind': 'text', 'required': True},
    {'key': 'beneficiaryCity', 'label': '59: Tỉnh/Thành phố người thụ hưởng', 'section': 'Beneficiary', 'kind': 'text', 'required': False},
    {'key': 'beneficiaryCountry', 'label': '59: Quốc gia người thụ hưởng', 'section': 'Beneficiary', 'kind': 'text', 'required': True},
    {'key': 'beneficiaryPostCode', 'label': '59: Mã bưu chính người thụ hưởng', 'section': 'Beneficiary', 'kind': 'text', 'required': False},
    {'key': 'beneficiaryDetailedAddress', 'label': '59: Địa chỉ chi tiết người thụ hưởng', 'section': 'Beneficiary', 'kind': 'textarea', 'required': False},
    {'key': 'swift', 'label': '57A: Mã SWIFT ngân hàng thông báo', 'section': 'Advising Bank', 'kind': 'text', 'required': True},
    {'key': 'bankName', 'label': '57A: Tên ngân hàng thông báo', 'section': 'Advising Bank', 'kind': 'text', 'required': True},
    {'key': 'bankBranch', 'label': '57A: Tên chi nhánh ngân hàng thông báo', 'section': 'Advising Bank', 'kind': 'text', 'required': False},
    {'key': 'bankAddress', 'label': '57A: Địa chỉ ngân hàng thông báo', 'section': 'Advising Bank', 'kind': 'text', 'required': False},
    {'key': 'expiryDate', 'label': '31D: Ngày hết hạn (Expiry Date)', 'section': 'Thông tin thanh toán', 'kind': 'date', 'required': True},
    {'key': 'expiryPlace', 'label': '31D: Địa điểm hết hạn (Place of Expiry)', 'section': 'Thông tin thanh toán', 'kind': 'text', 'required': True},
    {'key': 'availableWith', 'label': '41A: Có giá trị tại (Available with)', 'section': 'Thông tin thanh toán', 'kind': 'select', 'required': True},
    {'key': 'availableBy', 'label': '41A: Bằng (By)', 'section': 'Thông tin thanh toán', 'kind': 'select', 'required': True},
    {'key': 'draftsAt', 'label': '42A: Hối phiếu trả tiền tại (Drafts at)', 'section': 'Thông tin thanh toán', 'kind': 'choice', 'options': ['Có', 'Không'], 'required': False},
    {'key': 'draftTenor', 'label': '42C: Kỳ hạn hối phiếu', 'section': 'Thông tin thanh toán', 'kind': 'text', 'required': False},
    {'key': 'partialShipments', 'label': '43P: Giao hàng từng phần (Partial Shipments)', 'section': 'Hàng hóa/dịch vụ', 'kind': 'choice', 'options': ['Cho phép', 'Không cho phép'], 'required': False},
    {'key': 'transshipment', 'label': '43T: Chuyển tải (Transshipment)', 'section': 'Hàng hóa/dịch vụ', 'kind': 'choice', 'options': ['Cho phép', 'Không cho phép'], 'required': False},
    {'key': 'receiptPlace', 'label': '44A: Nơi nhận hàng/địa điểm gửi hàng', 'section': 'Hàng hóa/dịch vụ', 'kind': 'text', 'required': False},
    {'key': 'finalDestination', 'label': '44B: Nơi giao hàng cuối cùng', 'section': 'Hàng hóa/dịch vụ', 'kind': 'text', 'required': False},
    {'key': 'loadingPort', 'label': '44E: Cảng xếp hàng/Sân bay khởi hành', 'section': 'Hàng hóa/dịch vụ', 'kind': 'text', 'required': False},
    {'key': 'dischargePort', 'label': '44F: Cảng dỡ hàng/Sân bay đến', 'section': 'Hàng hóa/dịch vụ', 'kind': 'text', 'required': False},
    {'key': 'latestShipmentDate', 'label': '44C: Ngày giao hàng muộn nhất', 'section': 'Hàng hóa/dịch vụ', 'kind': 'date', 'required': False},
    {'key': 'shipmentPeriod', 'label': '44D: Thời hạn giao hàng', 'section': 'Hàng hóa/dịch vụ', 'kind': 'text', 'required': False},
    {'key': 'incoterms', 'label': 'Incoterms', 'section': 'Hàng hóa/dịch vụ', 'kind': 'select', 'required': True},
    {'key': 'deliveryTerms', 'label': 'Điều kiện giao hàng', 'section': 'Hàng hóa/dịch vụ', 'kind': 'select', 'required': False},
    {'key': 'goodsDescription', 'label': '45A: Mô tả hàng hóa/dịch vụ', 'section': 'Hàng hóa/dịch vụ', 'kind': 'textarea', 'required': True},
    {'key': 'presentationPeriod', 'label': '48: Thời hạn xuất trình chứng từ', 'section': 'Yêu cầu bộ chứng từ', 'kind': 'choice', 'options': ['Trong thời hạn hiệu lực của L/C', 'Theo số ngày quy định'], 'required': False},
    {'key': 'requiredDocuments', 'label': '46A: Chứng từ yêu cầu (Documents required)', 'section': 'Yêu cầu bộ chứng từ', 'kind': 'checkbox', 'options': [
        'Vận đơn đường biển sạch, đã xếp hàng lên tàu',
        'Hóa đơn thương mại có chữ ký',
        'Phiếu đóng gói do bên thụ hưởng phát hành',
        'Giấy chứng nhận xuất xứ',
        'Chứng thư chất lượng và số lượng',
        'Bản sao email thông báo giao hàng cho người yêu cầu',
        'Hối phiếu ký phát đòi ngân hàng phát hành',
        'Giấy chứng nhận bảo hiểm',
    ], 'required': False},
    {'key': 'additionalConditions', 'label': '47A: Điều kiện bổ sung (Additional conditions)', 'section': 'Điều khoản và điều kiện', 'kind': 'checkbox', 'options': [
        'Tất cả chứng từ phải được lập bằng tiếng Anh',
        'Chứng từ của bên thứ ba được chấp nhận, trừ hối phiếu và hóa đơn',
        'Chứng từ xuất trình không được thể hiện ngày phát hành trước ngày mở L/C',
        'Sai biệt về mô tả hàng hóa không được làm thay đổi bản chất giao dịch',
        'Chứng từ do cơ quan có thẩm quyền phát hành phải được ký và đóng dấu',
    ], 'required': False},
]
